### ISSUE TITLE
Chat page UI bug

### ISSUE THREAD

**Issue by minhhang107** [tuanthanh2067/seeksi#261]
**Describe the bug**
The `ChatWindow` in `Chat` page is displaying incorrectly on larger screen

**TODO**

- [ ] fix `ChatWindow` height
- [ ] fix `ChatSuggestLines` height
- [ ] fix position of photos (photos sent by current user should be aligned right)
- [ ] fix upload photos position (when user selects photos to upload, the input bar is pushed down)
- [ ] fix avatar (please make sure the size is big enough and all orientations should display correctly - please test horizontal/vertical/square images)

**To Reproduce**
1. Log in
2. Go to `Chat
3. Select a partner
4. Open DevTools, select `Dimension: Responsive` and drag the window to large screen

**Expected behavior**
`ChatWindow` should spread over the full height of the page

**Actual behavior**
`ChatWindow` only occupies half the height of the page

**Screenshots**
![screen](https://user-images.githubusercontent.com/55411709/156867638-99cc3801-b4dd-4c7e-adfc-2fa63d7914d7.jpg)
